#!/bin/zsh
# TODO: This no longer works and should be updated!
BASEDIR=$(dirname "$0")
cd $BASEDIR
python3 $BASEDIR/python/xml_make.py
echo "
Writing .pdf file from .xml file"
java -jar $BASEDIR/ead2pdf/ead2pdf.jar  $BASEDIR/outputs/Inventaris_it_IT.xml $BASEDIR/outputs/Inventaris_it_IT.pdf $BASEDIR/EADFiles/ead2fo.xsl
echo "Output .pdf file in $BASEDIR/outputs/Inventaris_nl_NL.pdf"