#!/bin/zsh
BASEDIR=$(dirname "$0")
cd $BASEDIR
python3 $BASEDIR/python/docx_to_xml.py
java -jar $BASEDIR/ead2pdf/ead2pdf.jar  $BASEDIR/EADFiles/Inventaris_nl_NL.xml $BASEDIR/Inventaris_nl_NL.pdf $BASEDIR/EADFiles/ead2fo.xsl

