name: Database controls
on:
  push:
jobs:
  Run_json_control_database:
    runs-on: ubuntu-latest
    name: Control of database
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Reconfigure locales
        run: |
          sudo locale-gen it_IT.UTF-8
          sudo locale-gen en_GB.UTF-8
          sudo locale-gen nl_NL.UTF-8
      - name: Execute json_control_database
        run: |
          python python/json_control_database.py
          if [ $? -eq 0 ]
          then
            echo "The database seems to be correct and passed all tests!"
          else
            echo "### WARNING: The Individuals database seems to be incorrect! ###"
            echo "See the above error message for possible problems."
            exit 1
          fi
  Check_sorting_of_individuals:
    name: Check sorting of Individuals.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Control if inputs/Individuals.json is 'sorted' correctly
        run: |
          if grep -rq '"titles": [["conte", null]],' inputs
          then
            echo "The database seems to be correctly saved"
          else
            echo "### WARNING: The Individuals database seems to be incorrect! ###"
            echo "Did you give the Visual Studio Code enough time for formatting?."
            echo "Retry by doing ctrl+S on individuals.json and waiting a bit longer for formatting to complete."
            exit 1
          fi
