name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Run_json_control_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests bs4
    - name: Reconfigure locales
      run: |
        sudo locale-gen it_IT.UTF-8
        sudo locale-gen en_GB.UTF-8
        sudo locale-gen nl_NL.UTF-8
    - name: Execute json_control_database
      run: |
        python python/json_control_database.py
        if [ $? -eq 0 ]
        then
          echo "The database seems to be correct and passed all tests!"
        else
          echo "### WARNING: The Individuals database seems to be incorrect! ###"
          echo "See the above error message for possible problems."
          exit 1
        fi
  Run_json_sort_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Execute json_control_database
      run: |
        python python/json_sort_database.py
    - name: Compare output with current file
      run: |
        if cmp inputs/Individuals.json outputs/Individuals.json; then
              echo '### SUCCESS: The database is correctly sorted! ###'
        else
            echo "### WARNING: The Individuals database does not seem to be sorted! ###"
            echo "Make sure to run python/json_sort_database.py and copy outputs/individuals.json to inputs before making a commit!"
            exit 1
        fi
